#!/bin/sh

BAND=GSM900
KAL=~/x/gnuradio/projects/kalibrate-rtl/src/kal

if [ x"$1" = x"" ]
then
	DEVICE=0
else
	DEVICE=$1
fi
ARFCN=`$KAL -d $DEVICE -s $BAND |sort -nk7 |tail -1 |cut -f2 -d: |cut -f2 -d ' '`
PPM=`$KAL -d $DEVICE -c $ARFCN |grep 'average absolute error' |cut -f4 -d' '`
echo $PPM
